# Generated by Django 5.2.3 on 2025-07-05 13:10

import models.masters.company_registration.helpers
import models.masters.company_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandType', models.CharField(db_column='brand_type', max_length=100)),
                ('license', models.CharField(db_column='license', max_length=100)),
                ('applicationYear', models.CharField(db_column='application_year', default='2025-2026', max_length=9)),
                ('companyName', models.CharField(db_column='company_name', max_length=255, validators=[models.masters.company_registration.helpers.validate_name])),
                ('pan', models.CharField(db_column='pan', max_length=10, validators=[models.masters.company_registration.helpers.validate_pan])),
                ('officeAddress', models.TextField(db_column='office_address', validators=[models.masters.company_registration.helpers.validate_address])),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('factoryAddress', models.TextField(db_column='factory_address', validators=[models.masters.company_registration.helpers.validate_address])),
                ('pinCode', models.PositiveIntegerField(db_column='pin_code')),
                ('companyMobileNumber', models.BigIntegerField(db_column='company_mobile_number', validators=[models.masters.company_registration.helpers.validate_mobile_number])),
                ('companyEmailId', models.EmailField(blank=True, db_column='company_email_id', max_length=254, validators=[models.masters.company_registration.helpers.validate_email])),
                ('memberName', models.CharField(db_column='member_name', max_length=255, validators=[models.masters.company_registration.helpers.validate_name])),
                ('memberDesignation', models.CharField(db_column='member_designation', max_length=255)),
                ('memberMobileNumber', models.BigIntegerField(db_column='member_mobile_number', validators=[models.masters.company_registration.helpers.validate_mobile_number])),
                ('memberEmailId', models.EmailField(blank=True, db_column='member_email_id', max_length=254, validators=[models.masters.company_registration.helpers.validate_email])),
                ('memberAddress', models.TextField(db_column='member_address', validators=[models.masters.company_registration.helpers.validate_address])),
                ('paymentId', models.CharField(db_column='payment_id', max_length=100)),
                ('paymentDate', models.DateField(db_column='payment_date')),
                ('paymentAmount', models.DecimalField(db_column='payment_amount', decimal_places=2, max_digits=10)),
                ('paymentRemarks', models.TextField(blank=True, db_column='payment_remarks', null=True)),
                ('undertaking', models.FileField(upload_to=models.masters.company_registration.models.upload_document_path)),
            ],
            options={
                'db_table': 'company_details',
            },
        ),
    ]
