# Generated by Django 5.2.3 on 2025-07-05 13:10

import django.db.models.deletion
import models.masters.license_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exciseDistrict', models.CharField(db_column='excise_district', max_length=100)),
                ('licenseCategory', models.CharField(db_column='license_category', max_length=100)),
                ('exciseSubDivision', models.CharField(db_column='excise_sub_division', max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('licenseType', models.CharField(db_column='license_type', max_length=100)),
                ('establishmentName', models.CharField(db_column='establishment_name', max_length=255)),
                ('mobileNumber', models.BigIntegerField(db_column='mobile_number')),
                ('emailId', models.EmailField(db_column='email_id', max_length=254)),
                ('licenseNo', models.BigIntegerField(blank=True, db_column='license_no', null=True)),
                ('initialGrantDate', models.DateField(blank=True, db_column='initial_grant_date', null=True)),
                ('renewedFrom', models.DateField(blank=True, db_column='renewed_from', null=True)),
                ('validUpTo', models.DateField(blank=True, db_column='valid_up_to', null=True)),
                ('yearlyLicenseFee', models.CharField(blank=True, db_column='yearly_license_fee', max_length=100, null=True)),
                ('licenseNature', models.CharField(db_column='license_nature', max_length=100)),
                ('functioningStatus', models.CharField(db_column='functioning_status', max_length=100)),
                ('modeofOperation', models.CharField(db_column='mode_of_operation', default='none', max_length=100)),
                ('siteSubDivision', models.CharField(db_column='site_sub_division', max_length=100)),
                ('policeStation', models.CharField(db_column='police_station', max_length=100)),
                ('locationCategory', models.CharField(db_column='location_category', max_length=100)),
                ('locationName', models.CharField(db_column='location_name', max_length=100)),
                ('wardName', models.CharField(db_column='ward_name', max_length=100)),
                ('businessAddress', models.TextField(db_column='business_address')),
                ('roadName', models.CharField(db_column='road_name', max_length=100)),
                ('pinCode', models.IntegerField(db_column='pin_code')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=50, null=True)),
                ('companyName', models.CharField(blank=True, db_column='company_name', max_length=255, null=True)),
                ('companyAddress', models.TextField(blank=True, db_column='company_address', null=True)),
                ('companyPan', models.CharField(blank=True, db_column='company_pan', max_length=20, null=True)),
                ('companyCin', models.CharField(blank=True, db_column='company_cin', max_length=30, null=True)),
                ('incorporationDate', models.DateField(blank=True, db_column='incorporation_date', null=True)),
                ('companyPhoneNumber', models.BigIntegerField(blank=True, db_column='company_phone_number', null=True)),
                ('companyEmailId', models.EmailField(blank=True, db_column='company_email_id', max_length=254, null=True)),
                ('status', models.CharField(max_length=100)),
                ('memberName', models.CharField(db_column='member_name', max_length=100)),
                ('fatherHusbandName', models.CharField(db_column='father_husband_name', max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('pan', models.CharField()),
                ('memberMobileNumber', models.BigIntegerField(db_column='member_mobile_number')),
                ('memberEmailId', models.EmailField(db_column='member_email_id', max_length=254)),
                ('photo', models.ImageField(upload_to=models.masters.license_application.models.upload_document_path)),
                ('current_stage', models.CharField(choices=[('draft', 'Draft'), ('permit_section', 'Permit Section'), ('joint_commissioner', 'Joint Commissioner'), ('commissioner', 'Commissioner'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'license_application',
            },
        ),
        migrations.CreateModel(
            name='LicenseApplicationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('permit_section', 'Permit Section'), ('joint_commissioner', 'Joint Commissioner'), ('commissioner', 'Commissioner'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('license_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='license_application.licenseapplication')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser')),
            ],
            options={
                'db_table': 'license_application_transaction',
            },
        ),
    ]
