# Generated by Django 5.2.3 on 2025-07-05 13:10

import auth.user.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(error_messages={'blank': 'First name cannot be blank.'}, max_length=50, validators=[auth.user.validators.validate_name])),
                ('last_name', models.CharField(error_messages={'blank': 'Last name cannot be blank.'}, max_length=50, validators=[auth.user.validators.validate_name])),
                ('phone_number', models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=10, unique=True, validators=[auth.user.validators.validate_phone_number])),
                ('district', models.PositiveIntegerField(default=117)),
                ('subdivision', models.PositiveIntegerField(default=1001)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'custom_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
