# Generated by Django 5.2.3 on 2025-07-05 13:10

import models.masters.contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorateAndDistrictOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(blank=True, db_column='phone_number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[models.masters.contact_us.validators.validate_email])),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceRedressalOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[models.masters.contact_us.validators.validate_non_empty])),
                ('designation', models.CharField(max_length=255, validators=[models.masters.contact_us.validators.validate_designation])),
                ('phoneNumber', models.CharField(db_column='phone_number', default='00000000000', max_length=20, validators=[models.masters.contact_us.validators.validate_phone_number])),
                ('email', models.EmailField(max_length=254, validators=[models.masters.contact_us.validators.validate_email])),
                ('officeLevel', models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], db_column='office_level', default='Excise Head Office', max_length=255, validators=[models.masters.contact_us.validators.validate_office_level])),
                ('officeSubLevel', models.CharField(blank=True, db_column='office_sub_level', max_length=255, null=True, validators=[models.masters.contact_us.validators.validate_non_empty])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodalOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Excise Department', max_length=255, validators=[models.masters.contact_us.validators.validate_department_name])),
                ('cell', models.CharField(default='IT Cell', max_length=255, validators=[models.masters.contact_us.validators.validate_non_empty])),
                ('phoneNumber', models.CharField(db_column='phone_number', default='(035) 9220-3963', max_length=20, validators=[models.masters.contact_us.validators.validate_phone_number])),
                ('email', models.EmailField(default='helpdesk-excise@sikkim.gov.in', max_length=254, validators=[models.masters.contact_us.validators.validate_email])),
            ],
        ),
        migrations.CreateModel(
            name='PublicInformationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[models.masters.contact_us.validators.validate_non_empty])),
                ('designation', models.CharField(max_length=255, validators=[models.masters.contact_us.validators.validate_designation])),
                ('phoneNumber', models.CharField(db_column='phone_number', default='00000000000', max_length=20, validators=[models.masters.contact_us.validators.validate_phone_number])),
                ('email', models.EmailField(max_length=254, validators=[models.masters.contact_us.validators.validate_email])),
                ('locationType', models.CharField(choices=[('Headquarter', 'Headquarter'), ('District', 'District'), ('unset', 'unset')], db_column='location_type', default='unset', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(default='Not Available', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
