# Generated by Django 5.2.3 on 2025-07-05 13:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('can_add', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('can_update', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('can_delete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('can_view', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('role_precedence', models.IntegerField(default=0, help_text='Higher number = higher privileges', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['-role_precedence'],
            },
        ),
    ]
