# Generated by Django 5.2.3 on 2025-07-05 13:10

import django.db.models.deletion
import models.masters.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseCategoryDescription', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseType', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(default='Sikkim')),
                ('StateNameLL', models.CharField(max_length=30, validators=[models.masters.core.validators.validate_name])),
                ('StateCode', models.IntegerField(default=11, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=30, validators=[models.masters.core.validators.validate_name])),
                ('DistrictNameLL', models.CharField(max_length=30, null=True, validators=[models.masters.core.validators.validate_name])),
                ('DistrictCode', models.IntegerField(default=117, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('StateCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.state', to_field='StateCode')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubDivisionName', models.CharField(max_length=30, null=True, validators=[models.masters.core.validators.validate_name])),
                ('SubDivisionNameLL', models.CharField(max_length=30, null=True, validators=[models.masters.core.validators.validate_name])),
                ('SubDivisionCode', models.IntegerField(default=1001, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('DistrictCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.district', to_field='DistrictCode')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoliceStationName', models.CharField(max_length=30, null=True, validators=[models.masters.core.validators.validate_name])),
                ('PoliceStationCode', models.IntegerField(default=11999, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('SubDivisionCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policestation', to='core.subdivision', to_field='SubDivisionCode')),
            ],
        ),
    ]
